version: 2

formats:
  - htmlzip
  - pdf
  - epub

project:
  name: netwix
  language: python

build:
  image: latest

python:
  version: 3.11
  install:
    - requirements:
      - requests
    - method: pip
